// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: modules/asset/types.proto

package asset

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_irisnet_irishub_sdk_go_types "github.com/irisnet/irishub-sdk-go/types"
	types "github.com/irisnet/irishub-sdk-go/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgIssueToken defines an SDK message for issuing a new token.
type MsgIssueToken struct {
	Symbol               string                                             `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name                 string                                             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scale                uint32                                             `protobuf:"varint,3,opt,name=scale,proto3" json:"scale,omitempty"`
	MinUnit              string                                             `protobuf:"bytes,4,opt,name=min_unit,json=minUnit,proto3" json:"min_unit,omitempty" yaml:"min_unit"`
	InitialSupply        uint64                                             `protobuf:"varint,5,opt,name=initial_supply,json=initialSupply,proto3" json:"initial_supply,omitempty" yaml:"initial_supply"`
	MaxSupply            uint64                                             `protobuf:"varint,6,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty" yaml:"max_supply"`
	Mintable             bool                                               `protobuf:"varint,7,opt,name=mintable,proto3" json:"mintable,omitempty"`
	Owner                github_com_irisnet_irishub_sdk_go_types.AccAddress `protobuf:"bytes,8,opt,name=owner,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.AccAddress" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *MsgIssueToken) Reset()         { *m = MsgIssueToken{} }
func (m *MsgIssueToken) String() string { return proto.CompactTextString(m) }
func (*MsgIssueToken) ProtoMessage()    {}
func (*MsgIssueToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f41032e3bb1759d, []int{0}
}
func (m *MsgIssueToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgIssueToken.Unmarshal(m, b)
}
func (m *MsgIssueToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgIssueToken.Marshal(b, m, deterministic)
}
func (m *MsgIssueToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIssueToken.Merge(m, src)
}
func (m *MsgIssueToken) XXX_Size() int {
	return xxx_messageInfo_MsgIssueToken.Size(m)
}
func (m *MsgIssueToken) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIssueToken.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIssueToken proto.InternalMessageInfo

// MsgEditToken defines an SDK message for editing a new token.
type MsgEditToken struct {
	Symbol               string                                             `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name                 string                                             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MaxSupply            uint64                                             `protobuf:"varint,3,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty" yaml:"max_supply"`
	Mintable             Bool                                               `protobuf:"bytes,4,opt,name=mintable,proto3,casttype=Bool" json:"mintable,omitempty"`
	Owner                github_com_irisnet_irishub_sdk_go_types.AccAddress `protobuf:"bytes,5,opt,name=owner,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.AccAddress" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *MsgEditToken) Reset()         { *m = MsgEditToken{} }
func (m *MsgEditToken) String() string { return proto.CompactTextString(m) }
func (*MsgEditToken) ProtoMessage()    {}
func (*MsgEditToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f41032e3bb1759d, []int{1}
}
func (m *MsgEditToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgEditToken.Unmarshal(m, b)
}
func (m *MsgEditToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgEditToken.Marshal(b, m, deterministic)
}
func (m *MsgEditToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEditToken.Merge(m, src)
}
func (m *MsgEditToken) XXX_Size() int {
	return xxx_messageInfo_MsgEditToken.Size(m)
}
func (m *MsgEditToken) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEditToken.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEditToken proto.InternalMessageInfo

// MsgTransferTokenOwner defines an SDK message for transferring the token owner.
type MsgTransferTokenOwner struct {
	SrcOwner             github_com_irisnet_irishub_sdk_go_types.AccAddress `protobuf:"bytes,1,opt,name=src_owner,json=srcOwner,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.AccAddress" json:"src_owner,omitempty"`
	DstOwner             github_com_irisnet_irishub_sdk_go_types.AccAddress `protobuf:"bytes,2,opt,name=dst_owner,json=dstOwner,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.AccAddress" json:"dst_owner,omitempty"`
	Symbol               string                                             `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *MsgTransferTokenOwner) Reset()         { *m = MsgTransferTokenOwner{} }
func (m *MsgTransferTokenOwner) String() string { return proto.CompactTextString(m) }
func (*MsgTransferTokenOwner) ProtoMessage()    {}
func (*MsgTransferTokenOwner) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f41032e3bb1759d, []int{2}
}
func (m *MsgTransferTokenOwner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgTransferTokenOwner.Unmarshal(m, b)
}
func (m *MsgTransferTokenOwner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgTransferTokenOwner.Marshal(b, m, deterministic)
}
func (m *MsgTransferTokenOwner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferTokenOwner.Merge(m, src)
}
func (m *MsgTransferTokenOwner) XXX_Size() int {
	return xxx_messageInfo_MsgTransferTokenOwner.Size(m)
}
func (m *MsgTransferTokenOwner) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferTokenOwner.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferTokenOwner proto.InternalMessageInfo

// MsgMintToken defines an SDK message for minting a new token.
type MsgMintToken struct {
	Symbol               string                                             `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Amount               uint64                                             `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	To                   github_com_irisnet_irishub_sdk_go_types.AccAddress `protobuf:"bytes,3,opt,name=to,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.AccAddress" json:"to,omitempty"`
	Owner                github_com_irisnet_irishub_sdk_go_types.AccAddress `protobuf:"bytes,4,opt,name=owner,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.AccAddress" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *MsgMintToken) Reset()         { *m = MsgMintToken{} }
func (m *MsgMintToken) String() string { return proto.CompactTextString(m) }
func (*MsgMintToken) ProtoMessage()    {}
func (*MsgMintToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f41032e3bb1759d, []int{3}
}
func (m *MsgMintToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMintToken.Unmarshal(m, b)
}
func (m *MsgMintToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMintToken.Marshal(b, m, deterministic)
}
func (m *MsgMintToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintToken.Merge(m, src)
}
func (m *MsgMintToken) XXX_Size() int {
	return xxx_messageInfo_MsgMintToken.Size(m)
}
func (m *MsgMintToken) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintToken.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintToken proto.InternalMessageInfo

// Token defines a standard for the fungible token
type Token struct {
	Symbol               string                                             `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name                 string                                             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scale                uint32                                             `protobuf:"varint,3,opt,name=scale,proto3" json:"scale,omitempty"`
	MinUnit              string                                             `protobuf:"bytes,4,opt,name=min_unit,json=minUnit,proto3" json:"min_unit,omitempty" yaml:"min_unit"`
	InitialSupply        uint64                                             `protobuf:"varint,5,opt,name=initial_supply,json=initialSupply,proto3" json:"initial_supply,omitempty" yaml:"initial_supply"`
	MaxSupply            uint64                                             `protobuf:"varint,6,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty" yaml:"max_supply"`
	Mintable             bool                                               `protobuf:"varint,7,opt,name=mintable,proto3" json:"mintable,omitempty"`
	Owner                github_com_irisnet_irishub_sdk_go_types.AccAddress `protobuf:"bytes,8,opt,name=owner,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.AccAddress" json:"owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f41032e3bb1759d, []int{4}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

// token parameters
type Params struct {
	TokenTaxRate         github_com_irisnet_irishub_sdk_go_types.Dec `protobuf:"bytes,1,opt,name=token_tax_rate,json=tokenTaxRate,proto3,customtype=github.com/irisnet/irishub-sdk-go/types.Dec" json:"token_tax_rate" yaml:"token_tax_rate"`
	IssueTokenBaseFee    types.Coin                                  `protobuf:"bytes,2,opt,name=issue_token_base_fee,json=issueTokenBaseFee,proto3" json:"issue_token_base_fee" yaml:"issue_token_base_fee"`
	MintTokenFeeRatio    github_com_irisnet_irishub_sdk_go_types.Dec `protobuf:"bytes,3,opt,name=mint_token_fee_ratio,json=mintTokenFeeRatio,proto3,customtype=github.com/irisnet/irishub-sdk-go/types.Dec" json:"mint_token_fee_ratio" yaml:"mint_token_fee_ratio"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f41032e3bb1759d, []int{5}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgIssueToken)(nil), "irishub.modules.asset.MsgIssueToken")
	proto.RegisterType((*MsgEditToken)(nil), "irishub.modules.asset.MsgEditToken")
	proto.RegisterType((*MsgTransferTokenOwner)(nil), "irishub.modules.asset.MsgTransferTokenOwner")
	proto.RegisterType((*MsgMintToken)(nil), "irishub.modules.asset.MsgMintToken")
	proto.RegisterType((*Token)(nil), "irishub.modules.asset.Token")
	proto.RegisterType((*Params)(nil), "irishub.modules.asset.Params")
}

func init() { proto.RegisterFile("modules/asset/types.proto", fileDescriptor_3f41032e3bb1759d) }

var fileDescriptor_3f41032e3bb1759d = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xae, 0x5d, 0x27, 0x4d, 0x96, 0xa6, 0x28, 0x4b, 0x53, 0xb9, 0xad, 0x84, 0x23, 0x83, 0x50,
	0x24, 0xd4, 0x58, 0x2a, 0x3f, 0x87, 0x9e, 0xa8, 0x81, 0x4a, 0x48, 0x8d, 0x40, 0xdb, 0x72, 0xe1,
	0x62, 0x6d, 0xec, 0xad, 0xbb, 0xaa, 0xed, 0x8d, 0xbc, 0x1b, 0x91, 0x9c, 0x79, 0x11, 0x1e, 0xa7,
	0x0f, 0xc0, 0x05, 0x0e, 0x96, 0x2a, 0x38, 0x70, 0xe1, 0x92, 0x63, 0x4f, 0xc8, 0xbb, 0xce, 0x9f,
	0xa8, 0xd4, 0xd2, 0x96, 0x1b, 0x37, 0xcf, 0xce, 0xcc, 0x37, 0x33, 0xdf, 0xb7, 0xeb, 0x01, 0xeb,
	0x31, 0x0b, 0xfa, 0x11, 0xe1, 0x0e, 0xe6, 0x9c, 0x08, 0x47, 0x0c, 0x7b, 0x84, 0xb7, 0x7b, 0x29,
	0x13, 0x0c, 0x36, 0x68, 0x4a, 0xf9, 0x71, 0xbf, 0xdb, 0x2e, 0x42, 0xda, 0x32, 0x64, 0xe3, 0x91,
	0x38, 0xa6, 0x69, 0xe0, 0xf5, 0x70, 0x2a, 0x86, 0x8e, 0x8c, 0x74, 0x42, 0x16, 0xb2, 0xe9, 0x97,
	0x4a, 0xdf, 0xa8, 0x4b, 0xac, 0x59, 0x44, 0xfb, 0xbb, 0x0e, 0x6a, 0x1d, 0x1e, 0xbe, 0xe1, 0xbc,
	0x4f, 0x0e, 0xd9, 0x09, 0x49, 0xe0, 0x1a, 0x28, 0xf3, 0x61, 0xdc, 0x65, 0x91, 0xa9, 0x35, 0xb5,
	0x56, 0x15, 0x15, 0x16, 0x84, 0xc0, 0x48, 0x70, 0x4c, 0x4c, 0x5d, 0x9e, 0xca, 0x6f, 0xb8, 0x0a,
	0x4a, 0xdc, 0xc7, 0x11, 0x31, 0x17, 0x9b, 0x5a, 0xab, 0x86, 0x94, 0x01, 0xdb, 0xa0, 0x12, 0xd3,
	0xc4, 0xeb, 0x27, 0x54, 0x98, 0x46, 0x1e, 0xed, 0xde, 0x1b, 0x65, 0xd6, 0xdd, 0x21, 0x8e, 0xa3,
	0x1d, 0x7b, 0xec, 0xb1, 0xd1, 0x52, 0x4c, 0x93, 0xf7, 0x09, 0x15, 0xf0, 0x05, 0x58, 0xa1, 0x09,
	0x15, 0x14, 0x47, 0x1e, 0xef, 0xf7, 0x7a, 0xd1, 0xd0, 0x2c, 0x35, 0xb5, 0x96, 0xe1, 0xae, 0x8f,
	0x32, 0xab, 0xa1, 0xb2, 0xe6, 0xfd, 0x36, 0xaa, 0x15, 0x07, 0x07, 0xd2, 0x86, 0x4f, 0x01, 0x88,
	0xf1, 0x60, 0x9c, 0x5d, 0x96, 0xd9, 0x8d, 0x51, 0x66, 0xd5, 0x8b, 0x9a, 0x13, 0x9f, 0x8d, 0xaa,
	0x31, 0x1e, 0x14, 0x59, 0x1b, 0xb2, 0x4f, 0x81, 0xbb, 0x11, 0x31, 0x97, 0x9a, 0x5a, 0xab, 0x82,
	0x26, 0x36, 0xdc, 0x07, 0x25, 0xf6, 0x31, 0x21, 0xa9, 0x59, 0x69, 0x6a, 0xad, 0x65, 0xf7, 0xf9,
	0x79, 0x66, 0x6d, 0x87, 0x54, 0xe4, 0xdc, 0xfb, 0x2c, 0x76, 0x72, 0x1d, 0x12, 0x22, 0x9c, 0x42,
	0x8f, 0x2d, 0x1e, 0x9c, 0x6c, 0x85, 0xac, 0x60, 0x76, 0xd7, 0xf7, 0x77, 0x83, 0x20, 0x25, 0x9c,
	0x23, 0x05, 0x62, 0xff, 0xd0, 0xc0, 0x72, 0x87, 0x87, 0xaf, 0x03, 0x2a, 0xfe, 0x9e, 0xe4, 0xf9,
	0xe1, 0x16, 0xaf, 0x38, 0xdc, 0xc3, 0x99, 0xe1, 0x94, 0x08, 0x95, 0xf3, 0xcc, 0x32, 0x5c, 0xc6,
	0xa2, 0x8b, 0xc6, 0x2c, 0xdd, 0xc6, 0x98, 0x5f, 0x35, 0xd0, 0xe8, 0xf0, 0xf0, 0x30, 0xc5, 0x09,
	0x3f, 0x22, 0xa9, 0x1c, 0xf5, 0x6d, 0xee, 0x81, 0x07, 0xa0, 0xca, 0x53, 0xdf, 0x53, 0xb5, 0xb4,
	0x1b, 0xd5, 0xaa, 0xf0, 0xd4, 0x9f, 0x80, 0x06, 0x5c, 0x14, 0xa0, 0xfa, 0xcd, 0x40, 0x03, 0x2e,
	0x14, 0xe8, 0x54, 0x99, 0xc5, 0x59, 0x65, 0xec, 0x2f, 0x4a, 0xc2, 0x0e, 0x4d, 0x2e, 0x91, 0x70,
	0x0d, 0x94, 0x71, 0xcc, 0xfa, 0x89, 0x90, 0x2d, 0x19, 0xa8, 0xb0, 0xe0, 0x1e, 0xd0, 0x05, 0x93,
	0xa0, 0xd7, 0x6f, 0x53, 0x17, 0x6c, 0x2a, 0x99, 0x71, 0x1b, 0x92, 0x9d, 0xe9, 0xa0, 0xf4, 0xff,
	0xdd, 0xff, 0xa3, 0x77, 0xbf, 0x63, 0xfc, 0xfc, 0x6c, 0x69, 0xf6, 0x2f, 0x1d, 0x94, 0xdf, 0xe1,
	0x14, 0xc7, 0x1c, 0xa6, 0x60, 0x45, 0xe4, 0x6c, 0x7b, 0x02, 0x0f, 0xbc, 0x14, 0x0b, 0xa2, 0xc8,
	0x76, 0xf7, 0x4f, 0x33, 0x6b, 0xe1, 0x5b, 0x66, 0x3d, 0xbe, 0x6a, 0xad, 0x57, 0xc4, 0x9f, 0xb2,
	0x34, 0x0f, 0x69, 0xa3, 0x65, 0x79, 0x70, 0x88, 0x07, 0x08, 0x0b, 0x02, 0x7d, 0xb0, 0x4a, 0xf3,
	0xdf, 0xbb, 0xa7, 0xc2, 0xba, 0x98, 0x13, 0xef, 0x88, 0x28, 0x41, 0xef, 0x6c, 0xd7, 0xda, 0xe3,
	0x9d, 0xf2, 0x92, 0xd1, 0xc4, 0x7d, 0x90, 0x37, 0x32, 0xca, 0xac, 0xcd, 0x82, 0xff, 0x0b, 0x12,
	0x6d, 0x54, 0xa7, 0x93, 0x75, 0xe1, 0x62, 0x4e, 0xf6, 0x08, 0x81, 0x9f, 0x34, 0xb0, 0x9a, 0x93,
	0x58, 0xc4, 0x1e, 0x11, 0x92, 0xf7, 0x42, 0xd5, 0x85, 0xaf, 0xba, 0xe8, 0x7a, 0xf3, 0x6d, 0x4e,
	0xee, 0xce, 0x1f, 0xc0, 0x36, 0xaa, 0xc7, 0xe3, 0xb7, 0xb8, 0x47, 0x08, 0xca, 0xcf, 0x14, 0xdf,
	0xee, 0xb3, 0xd3, 0xb3, 0xfb, 0x0b, 0x1f, 0x9c, 0xcb, 0x4b, 0xcd, 0x2d, 0xda, 0x6e, 0x59, 0x6e,
	0xc4, 0x27, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd8, 0x3b, 0xfa, 0x10, 0x80, 0x07, 0x00, 0x00,
}

func (this *Token) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Token)
	if !ok {
		that2, ok := that.(Token)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Symbol != that1.Symbol {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Scale != that1.Scale {
		return false
	}
	if this.MinUnit != that1.MinUnit {
		return false
	}
	if this.InitialSupply != that1.InitialSupply {
		return false
	}
	if this.MaxSupply != that1.MaxSupply {
		return false
	}
	if this.Mintable != that1.Mintable {
		return false
	}
	if !bytes.Equal(this.Owner, that1.Owner) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.TokenTaxRate.Equal(that1.TokenTaxRate) {
		return false
	}
	if !this.IssueTokenBaseFee.Equal(&that1.IssueTokenBaseFee) {
		return false
	}
	if !this.MintTokenFeeRatio.Equal(that1.MintTokenFeeRatio) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
