// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: modules/bank/types.proto

package bank

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/irisnet/irishub-sdk-go/types"
	github_com_irisnet_irishub_sdk_go_types "github.com/irisnet/irishub-sdk-go/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgSend - high level transaction of the coin module
type MsgSend struct {
	FromAddress          github_com_irisnet_irishub_sdk_go_types.AccAddress `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.AccAddress" json:"from_address,omitempty" yaml:"from_address"`
	ToAddress            github_com_irisnet_irishub_sdk_go_types.AccAddress `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.AccAddress" json:"to_address,omitempty" yaml:"to_address"`
	Amount               github_com_irisnet_irishub_sdk_go_types.Coins      `protobuf:"bytes,3,opt,name=amount,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.Coins" json:"amount"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *MsgSend) Reset()         { *m = MsgSend{} }
func (m *MsgSend) String() string { return proto.CompactTextString(m) }
func (*MsgSend) ProtoMessage()    {}
func (*MsgSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_b74b992c2a306427, []int{0}
}
func (m *MsgSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgSend.Unmarshal(m, b)
}
func (m *MsgSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgSend.Marshal(b, m, deterministic)
}
func (m *MsgSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSend.Merge(m, src)
}
func (m *MsgSend) XXX_Size() int {
	return xxx_messageInfo_MsgSend.Size(m)
}
func (m *MsgSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSend proto.InternalMessageInfo

func (m *MsgSend) GetFromAddress() github_com_irisnet_irishub_sdk_go_types.AccAddress {
	if m != nil {
		return m.FromAddress
	}
	return nil
}

func (m *MsgSend) GetToAddress() github_com_irisnet_irishub_sdk_go_types.AccAddress {
	if m != nil {
		return m.ToAddress
	}
	return nil
}

func (m *MsgSend) GetAmount() github_com_irisnet_irishub_sdk_go_types.Coins {
	if m != nil {
		return m.Amount
	}
	return github_com_irisnet_irishub_sdk_go_types.Coins{}
}

// Input models transaction input
type Input struct {
	Address              github_com_irisnet_irishub_sdk_go_types.AccAddress `protobuf:"bytes,1,opt,name=address,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.AccAddress" json:"address,omitempty"`
	Coins                github_com_irisnet_irishub_sdk_go_types.Coins      `protobuf:"bytes,2,opt,name=coins,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.Coins" json:"coins"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_b74b992c2a306427, []int{1}
}
func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetAddress() github_com_irisnet_irishub_sdk_go_types.AccAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Input) GetCoins() github_com_irisnet_irishub_sdk_go_types.Coins {
	if m != nil {
		return m.Coins
	}
	return github_com_irisnet_irishub_sdk_go_types.Coins{}
}

// Output models transaction outputs
type Output struct {
	Address              github_com_irisnet_irishub_sdk_go_types.AccAddress `protobuf:"bytes,1,opt,name=address,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.AccAddress" json:"address,omitempty"`
	Coins                github_com_irisnet_irishub_sdk_go_types.Coins      `protobuf:"bytes,2,opt,name=coins,proto3,casttype=github.com/irisnet/irishub-sdk-go/types.Coins" json:"coins"`
	XXX_NoUnkeyedLiteral struct{}                                           `json:"-"`
	XXX_unrecognized     []byte                                             `json:"-"`
	XXX_sizecache        int32                                              `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_b74b992c2a306427, []int{2}
}
func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetAddress() github_com_irisnet_irishub_sdk_go_types.AccAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Output) GetCoins() github_com_irisnet_irishub_sdk_go_types.Coins {
	if m != nil {
		return m.Coins
	}
	return github_com_irisnet_irishub_sdk_go_types.Coins{}
}

// MsgMultiSend - high level transaction of the coin module
type MsgMultiSend struct {
	Inputs               []Input  `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs"`
	Outputs              []Output `protobuf:"bytes,2,rep,name=outputs,proto3" json:"outputs"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgMultiSend) Reset()         { *m = MsgMultiSend{} }
func (m *MsgMultiSend) String() string { return proto.CompactTextString(m) }
func (*MsgMultiSend) ProtoMessage()    {}
func (*MsgMultiSend) Descriptor() ([]byte, []int) {
	return fileDescriptor_b74b992c2a306427, []int{3}
}
func (m *MsgMultiSend) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgMultiSend.Unmarshal(m, b)
}
func (m *MsgMultiSend) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgMultiSend.Marshal(b, m, deterministic)
}
func (m *MsgMultiSend) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMultiSend.Merge(m, src)
}
func (m *MsgMultiSend) XXX_Size() int {
	return xxx_messageInfo_MsgMultiSend.Size(m)
}
func (m *MsgMultiSend) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMultiSend.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMultiSend proto.InternalMessageInfo

func (m *MsgMultiSend) GetInputs() []Input {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *MsgMultiSend) GetOutputs() []Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func init() {
	proto.RegisterType((*MsgSend)(nil), "irishub.modules.bank.MsgSend")
	proto.RegisterType((*Input)(nil), "irishub.modules.bank.Input")
	proto.RegisterType((*Output)(nil), "irishub.modules.bank.Output")
	proto.RegisterType((*MsgMultiSend)(nil), "irishub.modules.bank.MsgMultiSend")
}

func init() { proto.RegisterFile("modules/bank/types.proto", fileDescriptor_b74b992c2a306427) }

var fileDescriptor_b74b992c2a306427 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc8, 0xcd, 0x4f, 0x29,
	0xcd, 0x49, 0x2d, 0xd6, 0x4f, 0x4a, 0xcc, 0xcb, 0xd6, 0x2f, 0xa9, 0x2c, 0x48, 0x2d, 0xd6, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc9, 0x2c, 0xca, 0x2c, 0xce, 0x28, 0x4d, 0xd2, 0x83, 0xaa,
	0xd0, 0x03, 0xa9, 0x90, 0x52, 0x2b, 0xc9, 0xc8, 0x2c, 0x4a, 0x89, 0x2f, 0x48, 0x2c, 0x2a, 0xa9,
	0xd4, 0x07, 0x2b, 0xd4, 0x4f, 0xcf, 0x4f, 0xcf, 0x47, 0xb0, 0x20, 0xba, 0xa5, 0x04, 0xc1, 0x46,
	0x21, 0x1b, 0xa8, 0x74, 0x9a, 0x89, 0x8b, 0xdd, 0xb7, 0x38, 0x3d, 0x38, 0x35, 0x2f, 0x45, 0xa8,
	0x80, 0x8b, 0x27, 0xad, 0x28, 0x3f, 0x37, 0x3e, 0x31, 0x25, 0xa5, 0x28, 0xb5, 0xb8, 0x58, 0x82,
	0x51, 0x81, 0x51, 0x83, 0xc7, 0xc9, 0xf7, 0xd3, 0x3d, 0x79, 0xe1, 0xca, 0xc4, 0xdc, 0x1c, 0x2b,
	0x25, 0x64, 0x59, 0xa5, 0x5f, 0xf7, 0xe4, 0x8d, 0xd2, 0x33, 0x4b, 0x40, 0x8e, 0x49, 0xce, 0xcf,
	0xd5, 0x07, 0x39, 0x2c, 0x2f, 0xb5, 0x44, 0x1f, 0xea, 0x40, 0xdd, 0xe2, 0x94, 0x6c, 0xdd, 0xf4,
	0x7c, 0xa8, 0x5d, 0x8e, 0xc9, 0xc9, 0x8e, 0x10, 0x6d, 0x41, 0xdc, 0x20, 0x43, 0xa0, 0x1c, 0xa1,
	0x2c, 0x2e, 0xae, 0x92, 0x7c, 0xb8, 0x7d, 0x4c, 0x60, 0xfb, 0xbc, 0x3f, 0xdd, 0x93, 0x17, 0x84,
	0xd8, 0x87, 0x90, 0x23, 0xd7, 0x36, 0xce, 0x92, 0x7c, 0x98, 0x5d, 0x31, 0x5c, 0x6c, 0x89, 0xb9,
	0xf9, 0xa5, 0x79, 0x25, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0xbc, 0x7a, 0xb0, 0xb0, 0x74,
	0xce, 0xcf, 0xcc, 0x73, 0x32, 0x3d, 0x71, 0x4f, 0x9e, 0xe1, 0xd7, 0x3d, 0x79, 0x5d, 0x62, 0x6d,
	0x01, 0xe9, 0x2a, 0x0e, 0x82, 0x9a, 0x69, 0xc5, 0xf2, 0x62, 0x81, 0x3c, 0xa3, 0xd2, 0x6e, 0x46,
	0x2e, 0x56, 0xcf, 0xbc, 0x82, 0xd2, 0x12, 0xa1, 0x00, 0x2e, 0x76, 0xd4, 0x60, 0x34, 0x23, 0xd3,
	0x07, 0x30, 0x63, 0x84, 0xa2, 0xb8, 0x58, 0x93, 0x41, 0x56, 0x82, 0x83, 0x89, 0x5a, 0xce, 0x87,
	0x18, 0x09, 0x75, 0xfd, 0x1e, 0x46, 0x2e, 0x36, 0xff, 0xd2, 0x92, 0xa1, 0xea, 0xfc, 0x5e, 0x46,
	0x2e, 0x1e, 0xdf, 0xe2, 0x74, 0xdf, 0xd2, 0x9c, 0x92, 0x4c, 0x70, 0x7a, 0xb6, 0xe4, 0x62, 0xcb,
	0x04, 0x45, 0x06, 0xc8, 0x0f, 0xcc, 0x1a, 0xdc, 0x46, 0xd2, 0x7a, 0xd8, 0x72, 0x8f, 0x1e, 0x38,
	0xc2, 0x9c, 0x58, 0x40, 0x2e, 0x08, 0x82, 0x6a, 0x10, 0xb2, 0xe1, 0x62, 0xcf, 0x07, 0x87, 0x04,
	0xc8, 0xbd, 0x20, 0xbd, 0x32, 0xd8, 0xf5, 0x42, 0x82, 0x0b, 0xaa, 0x19, 0xa6, 0x05, 0xe2, 0x1e,
	0x27, 0x83, 0x28, 0x3d, 0xc2, 0xbe, 0x41, 0xce, 0xe9, 0x49, 0x6c, 0xe0, 0x3c, 0x69, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x71, 0x76, 0x1f, 0x20, 0x00, 0x04, 0x00, 0x00,
}

func (this *MsgSend) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgSend)
	if !ok {
		that2, ok := that.(MsgSend)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.FromAddress, that1.FromAddress) {
		return false
	}
	if !bytes.Equal(this.ToAddress, that1.ToAddress) {
		return false
	}
	if !this.Amount.Equal(&that1.Amount) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Input) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Input)
	if !ok {
		that2, ok := that.(Input)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Address, that1.Address) {
		return false
	}
	if !this.Coins.Equal(&that1.Coins) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Output) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Output)
	if !ok {
		that2, ok := that.(Output)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Address, that1.Address) {
		return false
	}
	if !this.Coins.Equal(&that1.Coins) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MsgMultiSend) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MsgMultiSend)
	if !ok {
		that2, ok := that.(MsgMultiSend)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Inputs) != len(that1.Inputs) {
		return false
	}
	for i := range this.Inputs {
		if !this.Inputs[i].Equal(&that1.Inputs[i]) {
			return false
		}
	}
	if len(this.Outputs) != len(that1.Outputs) {
		return false
	}
	for i := range this.Outputs {
		if !this.Outputs[i].Equal(&that1.Outputs[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
